### ISSUE TITLE
Incompatibility with newer versions of pdftk

### ISSUE THREAD

**Issue by nthiery** [thenexxuz/cups-epilog#2]
Thanks a lot for this drivers; it's going to save us a lot of headache having to go through a windows+coreldraw machine!

One small issue: newer versions of pdftk (I have 2.02) here use endeast rather than endE as option. See e.g.
http://makandracards.com/makandra/1487-rotate-a-pdf-under-ubuntu-linux

**Comment by thenexxuz** [comment]
I'm glad that someone is getting a good use of this :) The client that I wrote this for doesn't have the funds to have me dedicate more time to this. Nor do I have a machine to test against, but I am more than happy to accept pull requests for updates.

**Comment by nthiery** [comment]
Done!

**Comment by thenexxuz-zz** [comment]
Pull request merged.
